/**
 * ============================================
 *  DocuGen AI – Auto Documentation Bot
 * ============================================
 *
 * Main entry point that orchestrates the full pipeline:
 *   1. Read old and new JavaScript files
 *   2. Extract functions using AST analysis
 *   3. Detect changes (added / removed / modified)
 *   4. Generate documentation using AI
 *   5. Post a structured comment on the GitHub PR
 *
 * Usage:
 *   node bot.js --local          Run with sample files (demo mode)
 *   node bot.js old.js new.js    Run with custom files
 *   node bot.js                  Run in CI mode (uses env vars)
 */

require("dotenv").config();

const fs = require("fs");
const path = require("path");
const { extractFunctions } = require("./src/ast/analyzer");
const { detectChanges, formatSummary } = require("./src/utils/diff");
const { generateDocs } = require("./src/ai/generateDocs");
const { postComment } = require("./src/github/comment");

// ── Helpers ──────────────────────────────────────────────

/**
 * Read a file and return its contents as a string.
 * @param {string} filePath - Path to the file
 * @returns {string} File contents
 */
function readFile(filePath) {
    const resolved = path.resolve(filePath);
    if (!fs.existsSync(resolved)) {
        console.error(`❌ File not found: ${resolved}`);
        process.exit(1);
    }
    return fs.readFileSync(resolved, "utf-8");
}

// ── Main Pipeline ────────────────────────────────────────

async function main() {
    console.log("╔══════════════════════════════════════════╗");
    console.log("║  🤖 DocuGen AI – Auto Documentation Bot  ║");
    console.log("╚══════════════════════════════════════════╝\n");

    // Determine file paths based on mode
    const args = process.argv.slice(2);
    let oldFilePath, newFilePath;

    if (args.includes("--local") || args.length === 0) {
        // Local / demo mode → use sample files
        console.log("📂 Mode: Local (using sample files)\n");
        oldFilePath = path.join(__dirname, "samples", "old.js");
        newFilePath = path.join(__dirname, "samples", "new.js");
    } else if (args.length >= 2) {
        // Custom files provided as arguments
        console.log("📂 Mode: Custom files\n");
        oldFilePath = args[0];
        newFilePath = args[1];
    } else {
        console.error("Usage: node bot.js --local | node bot.js <old.js> <new.js>");
        process.exit(1);
    }

    // ── Step 1: Read source files ──
    console.log("📖 Step 1: Reading source files...");
    const oldCode = readFile(oldFilePath);
    const newCode = readFile(newFilePath);
    console.log(`   Old file: ${oldFilePath}`);
    console.log(`   New file: ${newFilePath}\n`);

    // ── Step 2: AST analysis ──
    console.log("🌳 Step 2: Parsing code with AST analyzer...");
    const oldFunctions = extractFunctions(oldCode);
    const newFunctions = extractFunctions(newCode);
    console.log(`   Old file: ${oldFunctions.length} function(s) found`);
    console.log(`   New file: ${newFunctions.length} function(s) found\n`);

    // ── Step 3: Detect changes ──
    console.log("🔍 Step 3: Detecting changes...");
    const changes = detectChanges(oldFunctions, newFunctions);
    const summary = formatSummary(changes);
    console.log(`   ${changes.added.length} added, ${changes.removed.length} removed, ${changes.modified.length} modified\n`);
    console.log("   Summary:");
    summary.split("\n").forEach((line) => console.log(`   ${line}`));
    console.log();

    // ── Step 4: Generate documentation ──
    console.log("🤖 Step 4: Generating documentation with AI...");
    const docs = await generateDocs(summary);
    console.log("   Documentation generated.\n");

    // ── Step 5: Build and post PR comment ──
    console.log("💬 Step 5: Posting PR comment...\n");

    const commentBody = buildComment(summary, docs);
    await postComment(commentBody);

    console.log("\n✅ Pipeline complete!");
}

/**
 * Build the formatted PR comment body.
 *
 * @param {string} summary - Change summary text
 * @param {string} docs - AI-generated documentation
 * @returns {string} Formatted markdown comment
 */
function buildComment(summary, docs) {
    return `## 🤖 DocuGen AI – Auto Documentation Bot

### Changes Detected
\`\`\`
${summary}
\`\`\`

### Generated Documentation
${docs}

---
*This comment was auto-generated by [DocuGen AI](https://github.com) 🚀*`;
}

// ── Run ──────────────────────────────────────────────────
main().catch((error) => {
    console.error("💥 Bot crashed:", error.message);
    process.exit(1);
});
